### ISSUE TITLE
OSPO API question

### ISSUE THREAD

**Issue by jeffwilcox** [dotnet/org-policy#15]
I was just browsing this code; do you still see upn/email swaps? Would love an example...

```
  // For some interesting reason, some people have their
            // email in the PreferredName field...

            var ms = link.MicrosoftInfo;

            if (ms.PreferredName != null && ms.PreferredName.Contains("@"))
            {
                if (string.IsNullOrEmpty(ms.EmailAddress))
                {
                    ms.EmailAddress = ms.PreferredName;
                    ms.PreferredName = null;
                }
```

https://github.com/dotnet/org-policy/blob/705ab416f15dc4c937803bd2bc2dd4b5d67f7c8f/src/Microsoft.DotnetOrg.Ospo/OspoClient.cs#L59

**Comment by terrajobst** [comment]
Just checked: doesn't seem to be an issue, at least when downloading them all. I'll remove this.
